In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [2]:
#Data Collection
Keyboard_name=[]
Keyboard_price=[]
Keyboard_rating=[]
#URL of all the pages
for i in range (0,42):
    url='https://www.flipkart.com/search?q=gaming+keyboards&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page={}'.format(i)
    response=requests.get(url)
    soup=BeautifulSoup(response.text)
#converting all the HTML code to readable format using Beautiful Soup
    
    for x in soup.find_all('div',attrs={'class':'_4ddWXP'}):
        kname=x.find('a',attrs={'class':'s1Q9rs'})
        kcost=x.find('div',attrs={'class':'_30jeq3'})
        krating=x.find('div',attrs={'class':'_3LWZlK'})
        
        # for keyboard names
        if kname:
            Keyboard_name.append(kname.text)
        else:
            Keyboard_name.append(np.NaN)
        #for keyboard costs
        if kcost:
            Keyboard_price.append(kcost.text)
        else:
            Keyboard_price.append(np.NaN)
        # for keyboard ratings
        if krating:
            Keyboard_rating.append(krating.text)
        else:
            Keyboard_rating.append(np.NaN)

In [29]:
# Creating a Dataframe
df=pd.DataFrame({'Name':Keyboard_name,'Price':Keyboard_price,'Rating':Keyboard_rating})
data=df
df

                                                  Name   Price Rating
0    LipiWorld Backlit Mini Wireless Keyboard Wirel...    ₹797    3.7
1    ZEBRONICS ZEB-TRANSFORMER-K Wired USB Gaming K...  ₹1,029    4.4
2    AMKETTE EvoFox Fireblade LED Backlit Wired USB...    ₹999    4.4
3              Logitech G213 Wired USB Gaming Keyboard  ₹4,109    4.7
4                   HP K500F Wired USB Gaming Keyboard  ₹1,234    4.5
..                                                 ...     ...    ...
875  Tobo  TV-out Cable KVM-41UA 4 Port Manual USB ...  ₹1,399    NaN
876       ZEBRONICS keyboard+mouse+otg=3-217 Combo Set  ₹3,200    NaN
877       ZEBRONICS keyboard+mouse+otg=3-248 Combo Set  ₹3,200    NaN
878  ZEBRONICS 102 Wireless Keyboard and Mouse Comb...    ₹959    2.3
879       ZEBRONICS keyboard+mouse+otg=3-253 Combo Set  ₹3,175    NaN

[880 rows x 3 columns]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 880 entries, 0 to 879
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    880 non-null    object
 1   Price   880 non-null    object
 2   Rating  205 non-null    object
dtypes: object(3)
memory usage: 20.8+ KB

In [31]:
# Converting rating column of string type into a float  type column.
df['Rating']=df['Rating'].astype(float)

In [32]:
# Removing currency symbol from price column to convert the column into float type.
for i in range(len(df)):
               df['Price'][i]=df['Price'][i][1:]

<ipython-input-32-0a4cbb89f16d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price'][i]=df['Price'][i][1:]

In [33]:
df

                                                  Name  Price  Rating
0    LipiWorld Backlit Mini Wireless Keyboard Wirel...    797     3.7
1    ZEBRONICS ZEB-TRANSFORMER-K Wired USB Gaming K...  1,029     4.4
2    AMKETTE EvoFox Fireblade LED Backlit Wired USB...    999     4.4
3              Logitech G213 Wired USB Gaming Keyboard  4,109     4.7
4                   HP K500F Wired USB Gaming Keyboard  1,234     4.5
..                                                 ...    ...     ...
875  Tobo  TV-out Cable KVM-41UA 4 Port Manual USB ...  1,399     NaN
876       ZEBRONICS keyboard+mouse+otg=3-217 Combo Set  3,200     NaN
877       ZEBRONICS keyboard+mouse+otg=3-248 Combo Set  3,200     NaN
878  ZEBRONICS 102 Wireless Keyboard and Mouse Comb...    959     2.3
879       ZEBRONICS keyboard+mouse+otg=3-253 Combo Set  3,175     NaN

[880 rows x 3 columns]

In [34]:
# Removing commas and converting Price column into float.
df['Price']=df["Price"].str.replace(",","").astype(float)

In [35]:
df

                                                  Name   Price  Rating
0    LipiWorld Backlit Mini Wireless Keyboard Wirel...   797.0     3.7
1    ZEBRONICS ZEB-TRANSFORMER-K Wired USB Gaming K...  1029.0     4.4
2    AMKETTE EvoFox Fireblade LED Backlit Wired USB...   999.0     4.4
3              Logitech G213 Wired USB Gaming Keyboard  4109.0     4.7
4                   HP K500F Wired USB Gaming Keyboard  1234.0     4.5
..                                                 ...     ...     ...
875  Tobo  TV-out Cable KVM-41UA 4 Port Manual USB ...  1399.0     NaN
876       ZEBRONICS keyboard+mouse+otg=3-217 Combo Set  3200.0     NaN
877       ZEBRONICS keyboard+mouse+otg=3-248 Combo Set  3200.0     NaN
878  ZEBRONICS 102 Wireless Keyboard and Mouse Comb...   959.0     2.3
879       ZEBRONICS keyboard+mouse+otg=3-253 Combo Set  3175.0     NaN

[880 rows x 3 columns]

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 880 entries, 0 to 879
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    880 non-null    object
 1   Price   880 non-null    float64
 2   Rating  205 non-null    float64
dtypes: float64(2), object(1)
memory usage: 20.8+ KB

In [37]:
df.describe()

              Price      Rating
count    880.000000  205.000000
mean    1600.686364    4.127317
std     2239.375907    0.611760
min      179.000000    2.000000
25%      599.000000    3.800000
50%      599.000000    4.300000
75%     1824.000000    4.500000
max    19800.000000    5.000000

In [38]:
df.to_csv(r'O:\DATA SCIENCE\datasets\Gaming Keyboards Flipkart.csv', index=False)